# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- UserStory/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    sudo apt-get install avr-libc
    sudo apt-get install gcc-avr
  displayName: 'Hack** install avr'

- task: CmdLine@2
  inputs:
    script: 'mkdir -p build'

- task: CMake@1
  inputs:
    cmakeArgs: '-DCMAKE_CXX_COMPILER=avr-gcc ..'
    workingDirectory: $(Build.SourcesDirectory)/build

- script: make
  displayName: 'Make Project'
  workingDirectory: $(Build.SourcesDirectory)/build

- script: sudo apt-get remove avr-libc gcc-avr
  displayName: "cleanup avr libs"
  condition: always()